{{- if and .Values.secret.enabled (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.djangoSecretKey | b64enc }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | b64enc }}
{{- end }}
